//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memberships
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int MembershipType_ID { get; set; }
        public Nullable<System.DateTime> Subscription_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public Nullable<bool> Approved { get; set; }
    }
}
