//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vss
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MediaContent
    {
        public string Content_Title { get; set; }
        public System.DateTime Uploaded_Date { get; set; }
        public Nullable<int> Membership_Level { get; set; }
        public int MediaContent_ID { get; set; }
        public string Content_Description { get; set; }
        public string Manifest { get; set; }
        public int ID { get; set; }
        public string MembershipType { get; set; }
        public bool IsActive { get; set; }
    }
}
